# Generated by Django 3.1.5 on 2021-02-06 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_addr', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField()),
                ('passengers', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('ride_status', models.CharField(choices=[('OP', 'Open'), ('CF', 'Confirmed'), ('CL', 'Completed')], default='OP', max_length=2)),
                ('can_be_shared', models.BooleanField()),
                ('vehicle_type', models.CharField(blank=True, max_length=30)),
                ('special_request', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(related_name='shared_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
